### ISSUE TITLE
Slow FPS on the version in this repo

### ISSUE THREAD

**Issue by julienkosinski** [timiscoding/matrix-rain#2]
Hello @timiscoding,

I have noticed an important FPS drop (4 FPS with 82 raindrops) within the first seconds of the animation with this version in the repo although the performance is quite good with the version on codepen.
I don't know what's going on there...
The best perf seems to be reached in your attempt 2.

An idea?
Thanks! :)

**Comment by timiscoding** [comment]
Did you notice that drop when building for [production](https://github.com/timiscoding/matrix-rain#production-build)? I did some brief testing and it seems to be a bit better than doing a dev build. Note: I updated the repo's package.json so you will need to do `npm i` first in order to build prod.

When I was building this, I found the animation to get really laggy above 50-60 drops. It's just my inefficient code I guess and depends how fast your pc is. 

I've updated it so you can configure the max number of raindrops to be active at any time. By default, it's set to 40. https://github.com/timiscoding/matrix-rain/blob/master/src/classes/Globals.js#L9

**Comment by julienkosinski** [comment]
Thank you very much for your help!

Yes I did notice the same in production and retested with the raindrop limitation, even with 40 it's something like 6 FPS.

I'm running it in Windows but I've tested to serve the project with Heroku or Dockerize it and unfortunately I have the same perf.

The surprising thing is that on codepen there's no low FPS problem. 50 raindrops and 57 to 60 FPS there ! https://codepen.io/timiscoding/project/editor/ZjNNOk
Maybe this codepen is different from the repo here (except the file limitation problem and the feature you add today)? Could you open the codepen to download to be able to test it easily?

I'm getting an excellent FPS (can't read it, change really fast unlike the React version but never under 50) with the attempt 2 and I reproduced this best perf locally.
https://codepen.io/timiscoding/pen/RjgxoY

About React wrapper, found this: https://github.com/NeroCor/react-p5-wrapper/pull/15 gonna give a try on this soon, doesn't explain the good perf in codepen though.

**Comment by timiscoding** [comment]
I've [fixed](https://github.com/timiscoding/matrix-rain/commit/c956572d55f8303a0f370e7a327c269ccafe6159) the problem. The unminified p5 library got loaded for both builds. I've changed it so that production builds use the minified lib so you should see an improvement there. If you want it fast for dev builds, just change [P5Wrapper to use the minified version](https://github.com/timiscoding/matrix-rain/blob/master/src/components/P5Wrapper.js#L8)

**Comment by julienkosinski** [comment]
Perfect, that's it! Thank you very much for your help and the fix! :)

**Comment by julienkosinski** [comment]
@timiscoding I just wish to inform you that after testing the code in my phone the version without React have better perf (always nearly 60FPS), the version here is unfortunately sometimes 10/20 FPS on a phone... If you think there may be something else going on here...
I won't reopen the issue because it might be really time consuming to optimize (not even sure this is possible, I suppose this might be the way React handle things here).
Thanks again for all the work! :)

**Comment by timiscoding** [comment]
The only area I can think could be causing the low fps is when the info box is enabled. Updating the DOM is an expensive operation and I am updating the stats every 5 frames. Do you see better performance when you hide info? 

In my testing, I changed the info box to update every second instead of every 5 frames and reran the benchmark and got higher results. You can test it out by changing line https://github.com/timiscoding/matrix-rain/blob/master/src/classes/DebugMatrix.js#L38

to `if (p.frameCount % 60 !== 0) return;`

**Comment by julienkosinski** [comment]
@timiscoding 

So, I'm sorry that was my bad because, two days ago, I had only tested the repo through the codepen you provided.
So, to test further I have deployed the build version of this repo in heroku and also the one in your attempt two.
The perf is way better in the build version in the repo than in codepen and the perf is virtually comparable to the one using the P5 DOM method.
I tested the trick you provided there to slow the update of the box. It doesn't seems to improve perf but you allowed me to compare fairly the DOM version (which updates every frames) and the one in the repo.

Thanks! Finally everything seems good! :D
